/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GrexNexusPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// node_modules/preact/dist/preact.module.js
var preact_module_exports = {};
__export(preact_module_exports, {
  Component: () => C,
  Fragment: () => S,
  cloneElement: () => W,
  createContext: () => X,
  createElement: () => k,
  createRef: () => M,
  h: () => k,
  hydrate: () => U,
  isValidElement: () => t,
  options: () => l,
  render: () => R,
  toChildArray: () => F
});
var n;
var l;
var u;
var t;
var i;
var r;
var o;
var e;
var f;
var c;
var a;
var s;
var h;
var p;
var v;
var y;
var d = {};
var w = [];
var _ = /acit|ex(?:s|g|n|p|$)|rph|grid|ows|mnc|ntw|ine[ch]|zoo|^ord|itera/i;
var g = Array.isArray;
function m(n2, l2) {
  for (var u2 in l2) n2[u2] = l2[u2];
  return n2;
}
function b(n2) {
  n2 && n2.parentNode && n2.parentNode.removeChild(n2);
}
function k(l2, u2, t2) {
  var i2, r2, o2, e2 = {};
  for (o2 in u2) "key" == o2 ? i2 = u2[o2] : "ref" == o2 ? r2 = u2[o2] : e2[o2] = u2[o2];
  if (arguments.length > 2 && (e2.children = arguments.length > 3 ? n.call(arguments, 2) : t2), "function" == typeof l2 && null != l2.defaultProps) for (o2 in l2.defaultProps) void 0 === e2[o2] && (e2[o2] = l2.defaultProps[o2]);
  return x(l2, e2, i2, r2, null);
}
function x(n2, t2, i2, r2, o2) {
  var e2 = { type: n2, props: t2, key: i2, ref: r2, __k: null, __: null, __b: 0, __e: null, __c: null, constructor: void 0, __v: null == o2 ? ++u : o2, __i: -1, __u: 0 };
  return null == o2 && null != l.vnode && l.vnode(e2), e2;
}
function M() {
  return { current: null };
}
function S(n2) {
  return n2.children;
}
function C(n2, l2) {
  this.props = n2, this.context = l2;
}
function $(n2, l2) {
  if (null == l2) return n2.__ ? $(n2.__, n2.__i + 1) : null;
  for (var u2; l2 < n2.__k.length; l2++) if (null != (u2 = n2.__k[l2]) && null != u2.__e) return u2.__e;
  return "function" == typeof n2.type ? $(n2) : null;
}
function I(n2) {
  if (n2.__P && n2.__d) {
    var u2 = n2.__v, t2 = u2.__e, i2 = [], r2 = [], o2 = m({}, u2);
    o2.__v = u2.__v + 1, l.vnode && l.vnode(o2), q(n2.__P, o2, u2, n2.__n, n2.__P.namespaceURI, 32 & u2.__u ? [t2] : null, i2, null == t2 ? $(u2) : t2, !!(32 & u2.__u), r2), o2.__v = u2.__v, o2.__.__k[o2.__i] = o2, D(i2, o2, r2), u2.__e = u2.__ = null, o2.__e != t2 && P(o2);
  }
}
function P(n2) {
  if (null != (n2 = n2.__) && null != n2.__c) return n2.__e = n2.__c.base = null, n2.__k.some(function(l2) {
    if (null != l2 && null != l2.__e) return n2.__e = n2.__c.base = l2.__e;
  }), P(n2);
}
function A(n2) {
  (!n2.__d && (n2.__d = true) && i.push(n2) && !H.__r++ || r != l.debounceRendering) && ((r = l.debounceRendering) || o)(H);
}
function H() {
  try {
    for (var n2, l2 = 1; i.length; ) i.length > l2 && i.sort(e), n2 = i.shift(), l2 = i.length, I(n2);
  } finally {
    i.length = H.__r = 0;
  }
}
function L(n2, l2, u2, t2, i2, r2, o2, e2, f2, c2, a2) {
  var s2, h2, p2, v2, y2, _2, g2, m2 = t2 && t2.__k || w, b2 = l2.length;
  for (f2 = T(u2, l2, m2, f2, b2), s2 = 0; s2 < b2; s2++) null != (p2 = u2.__k[s2]) && (h2 = -1 != p2.__i && m2[p2.__i] || d, p2.__i = s2, _2 = q(n2, p2, h2, i2, r2, o2, e2, f2, c2, a2), v2 = p2.__e, p2.ref && h2.ref != p2.ref && (h2.ref && J(h2.ref, null, p2), a2.push(p2.ref, p2.__c || v2, p2)), null == y2 && null != v2 && (y2 = v2), (g2 = !!(4 & p2.__u)) || h2.__k === p2.__k ? (f2 = j(p2, f2, n2, g2), g2 && h2.__e && (h2.__e = null)) : "function" == typeof p2.type && void 0 !== _2 ? f2 = _2 : v2 && (f2 = v2.nextSibling), p2.__u &= -7);
  return u2.__e = y2, f2;
}
function T(n2, l2, u2, t2, i2) {
  var r2, o2, e2, f2, c2, a2 = u2.length, s2 = a2, h2 = 0;
  for (n2.__k = new Array(i2), r2 = 0; r2 < i2; r2++) null != (o2 = l2[r2]) && "boolean" != typeof o2 && "function" != typeof o2 ? ("string" == typeof o2 || "number" == typeof o2 || "bigint" == typeof o2 || o2.constructor == String ? o2 = n2.__k[r2] = x(null, o2, null, null, null) : g(o2) ? o2 = n2.__k[r2] = x(S, { children: o2 }, null, null, null) : void 0 === o2.constructor && o2.__b > 0 ? o2 = n2.__k[r2] = x(o2.type, o2.props, o2.key, o2.ref ? o2.ref : null, o2.__v) : n2.__k[r2] = o2, f2 = r2 + h2, o2.__ = n2, o2.__b = n2.__b + 1, e2 = null, -1 != (c2 = o2.__i = O(o2, u2, f2, s2)) && (s2--, (e2 = u2[c2]) && (e2.__u |= 2)), null == e2 || null == e2.__v ? (-1 == c2 && (i2 > a2 ? h2-- : i2 < a2 && h2++), "function" != typeof o2.type && (o2.__u |= 4)) : c2 != f2 && (c2 == f2 - 1 ? h2-- : c2 == f2 + 1 ? h2++ : (c2 > f2 ? h2-- : h2++, o2.__u |= 4))) : n2.__k[r2] = null;
  if (s2) for (r2 = 0; r2 < a2; r2++) null != (e2 = u2[r2]) && 0 == (2 & e2.__u) && (e2.__e == t2 && (t2 = $(e2)), K(e2, e2));
  return t2;
}
function j(n2, l2, u2, t2) {
  var i2, r2;
  if ("function" == typeof n2.type) {
    for (i2 = n2.__k, r2 = 0; i2 && r2 < i2.length; r2++) i2[r2] && (i2[r2].__ = n2, l2 = j(i2[r2], l2, u2, t2));
    return l2;
  }
  n2.__e != l2 && (t2 && (l2 && n2.type && !l2.parentNode && (l2 = $(n2)), u2.insertBefore(n2.__e, l2 || null)), l2 = n2.__e);
  do {
    l2 = l2 && l2.nextSibling;
  } while (null != l2 && 8 == l2.nodeType);
  return l2;
}
function F(n2, l2) {
  return l2 = l2 || [], null == n2 || "boolean" == typeof n2 || (g(n2) ? n2.some(function(n3) {
    F(n3, l2);
  }) : l2.push(n2)), l2;
}
function O(n2, l2, u2, t2) {
  var i2, r2, o2, e2 = n2.key, f2 = n2.type, c2 = l2[u2], a2 = null != c2 && 0 == (2 & c2.__u);
  if (null === c2 && null == e2 || a2 && e2 == c2.key && f2 == c2.type) return u2;
  if (t2 > (a2 ? 1 : 0)) {
    for (i2 = u2 - 1, r2 = u2 + 1; i2 >= 0 || r2 < l2.length; ) if (null != (c2 = l2[o2 = i2 >= 0 ? i2-- : r2++]) && 0 == (2 & c2.__u) && e2 == c2.key && f2 == c2.type) return o2;
  }
  return -1;
}
function z(n2, l2, u2) {
  "-" == l2[0] ? n2.setProperty(l2, null == u2 ? "" : u2) : n2[l2] = null == u2 ? "" : "number" != typeof u2 || _.test(l2) ? u2 : u2 + "px";
}
function N(n2, l2, u2, t2, i2) {
  var r2, o2;
  n: if ("style" == l2) if ("string" == typeof u2) n2.style.cssText = u2;
  else {
    if ("string" == typeof t2 && (n2.style.cssText = t2 = ""), t2) for (l2 in t2) u2 && l2 in u2 || z(n2.style, l2, "");
    if (u2) for (l2 in u2) t2 && u2[l2] == t2[l2] || z(n2.style, l2, u2[l2]);
  }
  else if ("o" == l2[0] && "n" == l2[1]) r2 = l2 != (l2 = l2.replace(s, "$1")), o2 = l2.toLowerCase(), l2 = o2 in n2 || "onFocusOut" == l2 || "onFocusIn" == l2 ? o2.slice(2) : l2.slice(2), n2.l || (n2.l = {}), n2.l[l2 + r2] = u2, u2 ? t2 ? u2[a] = t2[a] : (u2[a] = h, n2.addEventListener(l2, r2 ? v : p, r2)) : n2.removeEventListener(l2, r2 ? v : p, r2);
  else {
    if ("http://www.w3.org/2000/svg" == i2) l2 = l2.replace(/xlink(H|:h)/, "h").replace(/sName$/, "s");
    else if ("width" != l2 && "height" != l2 && "href" != l2 && "list" != l2 && "form" != l2 && "tabIndex" != l2 && "download" != l2 && "rowSpan" != l2 && "colSpan" != l2 && "role" != l2 && "popover" != l2 && l2 in n2) try {
      n2[l2] = null == u2 ? "" : u2;
      break n;
    } catch (n3) {
    }
    "function" == typeof u2 || (null == u2 || false === u2 && "-" != l2[4] ? n2.removeAttribute(l2) : n2.setAttribute(l2, "popover" == l2 && 1 == u2 ? "" : u2));
  }
}
function V(n2) {
  return function(u2) {
    if (this.l) {
      var t2 = this.l[u2.type + n2];
      if (null == u2[c]) u2[c] = h++;
      else if (u2[c] < t2[a]) return;
      return t2(l.event ? l.event(u2) : u2);
    }
  };
}
function q(n2, u2, t2, i2, r2, o2, e2, f2, c2, a2) {
  var s2, h2, p2, v2, y2, d2, _2, k2, x2, M2, $2, I2, P2, A2, H2, T2 = u2.type;
  if (void 0 !== u2.constructor) return null;
  128 & t2.__u && (c2 = !!(32 & t2.__u), o2 = [f2 = u2.__e = t2.__e]), (s2 = l.__b) && s2(u2);
  n: if ("function" == typeof T2) try {
    if (k2 = u2.props, x2 = T2.prototype && T2.prototype.render, M2 = (s2 = T2.contextType) && i2[s2.__c], $2 = s2 ? M2 ? M2.props.value : s2.__ : i2, t2.__c ? _2 = (h2 = u2.__c = t2.__c).__ = h2.__E : (x2 ? u2.__c = h2 = new T2(k2, $2) : (u2.__c = h2 = new C(k2, $2), h2.constructor = T2, h2.render = Q), M2 && M2.sub(h2), h2.state || (h2.state = {}), h2.__n = i2, p2 = h2.__d = true, h2.__h = [], h2._sb = []), x2 && null == h2.__s && (h2.__s = h2.state), x2 && null != T2.getDerivedStateFromProps && (h2.__s == h2.state && (h2.__s = m({}, h2.__s)), m(h2.__s, T2.getDerivedStateFromProps(k2, h2.__s))), v2 = h2.props, y2 = h2.state, h2.__v = u2, p2) x2 && null == T2.getDerivedStateFromProps && null != h2.componentWillMount && h2.componentWillMount(), x2 && null != h2.componentDidMount && h2.__h.push(h2.componentDidMount);
    else {
      if (x2 && null == T2.getDerivedStateFromProps && k2 !== v2 && null != h2.componentWillReceiveProps && h2.componentWillReceiveProps(k2, $2), u2.__v == t2.__v || !h2.__e && null != h2.shouldComponentUpdate && false === h2.shouldComponentUpdate(k2, h2.__s, $2)) {
        u2.__v != t2.__v && (h2.props = k2, h2.state = h2.__s, h2.__d = false), u2.__e = t2.__e, u2.__k = t2.__k, u2.__k.some(function(n3) {
          n3 && (n3.__ = u2);
        }), w.push.apply(h2.__h, h2._sb), h2._sb = [], h2.__h.length && e2.push(h2);
        break n;
      }
      null != h2.componentWillUpdate && h2.componentWillUpdate(k2, h2.__s, $2), x2 && null != h2.componentDidUpdate && h2.__h.push(function() {
        h2.componentDidUpdate(v2, y2, d2);
      });
    }
    if (h2.context = $2, h2.props = k2, h2.__P = n2, h2.__e = false, I2 = l.__r, P2 = 0, x2) h2.state = h2.__s, h2.__d = false, I2 && I2(u2), s2 = h2.render(h2.props, h2.state, h2.context), w.push.apply(h2.__h, h2._sb), h2._sb = [];
    else do {
      h2.__d = false, I2 && I2(u2), s2 = h2.render(h2.props, h2.state, h2.context), h2.state = h2.__s;
    } while (h2.__d && ++P2 < 25);
    h2.state = h2.__s, null != h2.getChildContext && (i2 = m(m({}, i2), h2.getChildContext())), x2 && !p2 && null != h2.getSnapshotBeforeUpdate && (d2 = h2.getSnapshotBeforeUpdate(v2, y2)), A2 = null != s2 && s2.type === S && null == s2.key ? E(s2.props.children) : s2, f2 = L(n2, g(A2) ? A2 : [A2], u2, t2, i2, r2, o2, e2, f2, c2, a2), h2.base = u2.__e, u2.__u &= -161, h2.__h.length && e2.push(h2), _2 && (h2.__E = h2.__ = null);
  } catch (n3) {
    if (u2.__v = null, c2 || null != o2) if (n3.then) {
      for (u2.__u |= c2 ? 160 : 128; f2 && 8 == f2.nodeType && f2.nextSibling; ) f2 = f2.nextSibling;
      o2[o2.indexOf(f2)] = null, u2.__e = f2;
    } else {
      for (H2 = o2.length; H2--; ) b(o2[H2]);
      B(u2);
    }
    else u2.__e = t2.__e, u2.__k = t2.__k, n3.then || B(u2);
    l.__e(n3, u2, t2);
  }
  else null == o2 && u2.__v == t2.__v ? (u2.__k = t2.__k, u2.__e = t2.__e) : f2 = u2.__e = G(t2.__e, u2, t2, i2, r2, o2, e2, c2, a2);
  return (s2 = l.diffed) && s2(u2), 128 & u2.__u ? void 0 : f2;
}
function B(n2) {
  n2 && (n2.__c && (n2.__c.__e = true), n2.__k && n2.__k.some(B));
}
function D(n2, u2, t2) {
  for (var i2 = 0; i2 < t2.length; i2++) J(t2[i2], t2[++i2], t2[++i2]);
  l.__c && l.__c(u2, n2), n2.some(function(u3) {
    try {
      n2 = u3.__h, u3.__h = [], n2.some(function(n3) {
        n3.call(u3);
      });
    } catch (n3) {
      l.__e(n3, u3.__v);
    }
  });
}
function E(n2) {
  return "object" != typeof n2 || null == n2 || n2.__b > 0 ? n2 : g(n2) ? n2.map(E) : void 0 !== n2.constructor ? null : m({}, n2);
}
function G(u2, t2, i2, r2, o2, e2, f2, c2, a2) {
  var s2, h2, p2, v2, y2, w2, _2, m2 = i2.props || d, k2 = t2.props, x2 = t2.type;
  if ("svg" == x2 ? o2 = "http://www.w3.org/2000/svg" : "math" == x2 ? o2 = "http://www.w3.org/1998/Math/MathML" : o2 || (o2 = "http://www.w3.org/1999/xhtml"), null != e2) {
    for (s2 = 0; s2 < e2.length; s2++) if ((y2 = e2[s2]) && "setAttribute" in y2 == !!x2 && (x2 ? y2.localName == x2 : 3 == y2.nodeType)) {
      u2 = y2, e2[s2] = null;
      break;
    }
  }
  if (null == u2) {
    if (null == x2) return document.createTextNode(k2);
    u2 = document.createElementNS(o2, x2, k2.is && k2), c2 && (l.__m && l.__m(t2, e2), c2 = false), e2 = null;
  }
  if (null == x2) m2 === k2 || c2 && u2.data == k2 || (u2.data = k2);
  else {
    if (e2 = "textarea" == x2 && null != k2.defaultValue ? null : e2 && n.call(u2.childNodes), !c2 && null != e2) for (m2 = {}, s2 = 0; s2 < u2.attributes.length; s2++) m2[(y2 = u2.attributes[s2]).name] = y2.value;
    for (s2 in m2) y2 = m2[s2], "dangerouslySetInnerHTML" == s2 ? p2 = y2 : "children" == s2 || s2 in k2 || "value" == s2 && "defaultValue" in k2 || "checked" == s2 && "defaultChecked" in k2 || N(u2, s2, null, y2, o2);
    for (s2 in k2) y2 = k2[s2], "children" == s2 ? v2 = y2 : "dangerouslySetInnerHTML" == s2 ? h2 = y2 : "value" == s2 ? w2 = y2 : "checked" == s2 ? _2 = y2 : c2 && "function" != typeof y2 || m2[s2] === y2 || N(u2, s2, y2, m2[s2], o2);
    if (h2) c2 || p2 && (h2.__html == p2.__html || h2.__html == u2.innerHTML) || (u2.innerHTML = h2.__html), t2.__k = [];
    else if (p2 && (u2.innerHTML = ""), L("template" == t2.type ? u2.content : u2, g(v2) ? v2 : [v2], t2, i2, r2, "foreignObject" == x2 ? "http://www.w3.org/1999/xhtml" : o2, e2, f2, e2 ? e2[0] : i2.__k && $(i2, 0), c2, a2), null != e2) for (s2 = e2.length; s2--; ) b(e2[s2]);
    c2 && "textarea" != x2 || (s2 = "value", "progress" == x2 && null == w2 ? u2.removeAttribute("value") : null != w2 && (w2 !== u2[s2] || "progress" == x2 && !w2 || "option" == x2 && w2 != m2[s2]) && N(u2, s2, w2, m2[s2], o2), s2 = "checked", null != _2 && _2 != u2[s2] && N(u2, s2, _2, m2[s2], o2));
  }
  return u2;
}
function J(n2, u2, t2) {
  try {
    if ("function" == typeof n2) {
      var i2 = "function" == typeof n2.__u;
      i2 && n2.__u(), i2 && null == u2 || (n2.__u = n2(u2));
    } else n2.current = u2;
  } catch (n3) {
    l.__e(n3, t2);
  }
}
function K(n2, u2, t2) {
  var i2, r2;
  if (l.unmount && l.unmount(n2), (i2 = n2.ref) && (i2.current && i2.current != n2.__e || J(i2, null, u2)), null != (i2 = n2.__c)) {
    if (i2.componentWillUnmount) try {
      i2.componentWillUnmount();
    } catch (n3) {
      l.__e(n3, u2);
    }
    i2.base = i2.__P = null;
  }
  if (i2 = n2.__k) for (r2 = 0; r2 < i2.length; r2++) i2[r2] && K(i2[r2], u2, t2 || "function" != typeof n2.type);
  t2 || b(n2.__e), n2.__c = n2.__ = n2.__e = void 0;
}
function Q(n2, l2, u2) {
  return this.constructor(n2, u2);
}
function R(u2, t2, i2) {
  var r2, o2, e2, f2;
  t2 == document && (t2 = document.documentElement), l.__ && l.__(u2, t2), o2 = (r2 = "function" == typeof i2) ? null : i2 && i2.__k || t2.__k, e2 = [], f2 = [], q(t2, u2 = (!r2 && i2 || t2).__k = k(S, null, [u2]), o2 || d, d, t2.namespaceURI, !r2 && i2 ? [i2] : o2 ? null : t2.firstChild ? n.call(t2.childNodes) : null, e2, !r2 && i2 ? i2 : o2 ? o2.__e : t2.firstChild, r2, f2), D(e2, u2, f2);
}
function U(n2, l2) {
  R(n2, l2, U);
}
function W(l2, u2, t2) {
  var i2, r2, o2, e2, f2 = m({}, l2.props);
  for (o2 in l2.type && l2.type.defaultProps && (e2 = l2.type.defaultProps), u2) "key" == o2 ? i2 = u2[o2] : "ref" == o2 ? r2 = u2[o2] : f2[o2] = void 0 === u2[o2] && null != e2 ? e2[o2] : u2[o2];
  return arguments.length > 2 && (f2.children = arguments.length > 3 ? n.call(arguments, 2) : t2), x(l2.type, f2, i2 || l2.key, r2 || l2.ref, null);
}
function X(n2) {
  function l2(n3) {
    var u2, t2;
    return this.getChildContext || (u2 = /* @__PURE__ */ new Set(), (t2 = {})[l2.__c] = this, this.getChildContext = function() {
      return t2;
    }, this.componentWillUnmount = function() {
      u2 = null;
    }, this.shouldComponentUpdate = function(n4) {
      this.props.value != n4.value && u2.forEach(function(n5) {
        n5.__e = true, A(n5);
      });
    }, this.sub = function(n4) {
      u2.add(n4);
      var l3 = n4.componentWillUnmount;
      n4.componentWillUnmount = function() {
        u2 && u2.delete(n4), l3 && l3.call(n4);
      };
    }), n3.children;
  }
  return l2.__c = "__cC" + y++, l2.__ = n2, l2.Provider = l2.__l = (l2.Consumer = function(n3, l3) {
    return n3.children(l3);
  }).contextType = l2, l2;
}
n = w.slice, l = { __e: function(n2, l2, u2, t2) {
  for (var i2, r2, o2; l2 = l2.__; ) if ((i2 = l2.__c) && !i2.__) try {
    if ((r2 = i2.constructor) && null != r2.getDerivedStateFromError && (i2.setState(r2.getDerivedStateFromError(n2)), o2 = i2.__d), null != i2.componentDidCatch && (i2.componentDidCatch(n2, t2 || {}), o2 = i2.__d), o2) return i2.__E = i2;
  } catch (l3) {
    n2 = l3;
  }
  throw n2;
} }, u = 0, t = function(n2) {
  return null != n2 && void 0 === n2.constructor;
}, C.prototype.setState = function(n2, l2) {
  var u2;
  u2 = null != this.__s && this.__s != this.state ? this.__s : this.__s = m({}, this.state), "function" == typeof n2 && (n2 = n2(m({}, u2), this.props)), n2 && m(u2, n2), null != n2 && this.__v && (l2 && this._sb.push(l2), A(this));
}, C.prototype.forceUpdate = function(n2) {
  this.__v && (this.__e = true, n2 && this.__h.push(n2), A(this));
}, C.prototype.render = S, i = [], o = "function" == typeof Promise ? Promise.prototype.then.bind(Promise.resolve()) : setTimeout, e = function(n2, l2) {
  return n2.__v.__b - l2.__v.__b;
}, H.__r = 0, f = Math.random().toString(8), c = "__d" + f, a = "__a" + f, s = /(PointerCapture)$|Capture$/i, h = 0, p = V(false), v = V(true), y = 0;

// main.ts
function applyStyles(el, styles) {
  Object.assign(el.style, styles);
}
var VIEW_TYPE_GREX = "grex-component-view";
var VIEW_TYPE_GREX_DASHBOARD = "grex-dashboard-view";
var DEFAULT_SETTINGS = {
  githubToken: "",
  targetFolder: "GrexNexus/components/",
  sidecarToken: "",
  sidecarUrl: "http://localhost:7777",
  componentPermissions: {}
};
var ProvisioningModal = class extends import_obsidian.Modal {
  constructor(app, manifestCache) {
    super(app);
    this.manifestCache = manifestCache;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Component Dependencies & Environment" });
    const subtitle = contentEl.createEl("p", { text: "Active component requirements indexed in this vault." });
    subtitle.addClass("grex-text-muted");
    this.logContainer = contentEl.createDiv();
    this.logContainer.addClass("grex-log-container");
    this.log("Auditing installed component dependencies...");
    this.displaySummary();
  }
  log(msg, colorClass = "") {
    const line = this.logContainer.createDiv({ text: msg });
    line.addClass("grex-log-line");
    if (colorClass) {
      line.addClass(colorClass);
    }
    this.logContainer.scrollTop = this.logContainer.scrollHeight;
  }
  displaySummary() {
    let totalDeps = 0;
    this.manifestCache.forEach((comp) => {
      const deps = comp.manifest.dependencies;
      if (deps) {
        this.log(`
\u{1F4E6} ${comp.manifest.name} (${comp.folder.path})`, "grex-log-blue");
        if (deps.npm && deps.npm.length > 0) {
          this.log(`  \u2022 NPM: ${deps.npm.join(", ")}`);
          totalDeps += deps.npm.length;
        }
        if (deps.python && deps.python.length > 0) {
          this.log(`  \u2022 Python: ${deps.python.join(", ")}`);
          totalDeps += deps.python.length;
        }
        if (deps.mac && deps.mac.length > 0) {
          this.log(`  \u2022 macOS: ${deps.mac.join(", ")}`);
          totalDeps += deps.mac.length;
        }
        if (deps.windows && deps.windows.length > 0) {
          this.log(`  \u2022 Windows: ${deps.windows.join(", ")}`);
          totalDeps += deps.windows.length;
        }
      }
    });
    if (totalDeps === 0) {
      this.log("\nAll installed components run directly inside Obsidian without external packages.", "grex-log-green");
    } else {
      this.log(`
Audit complete: ${totalDeps} dependencies cataloged.`, "grex-log-green");
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ComponentSelectorModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, components, onChoose) {
    super(app);
    this.components = components;
    this.onChoose = onChoose;
  }
  getItems() {
    return this.components;
  }
  getItemText(comp) {
    return comp.manifest.name;
  }
  renderSuggestion(match, el) {
    el.empty();
    const comp = match.item;
    const container = el.createDiv();
    applyStyles(container, { display: "flex", flexDirection: "column", gap: "4px" });
    const titleEl = container.createDiv();
    applyStyles(titleEl, { fontWeight: "500" });
    super.renderSuggestion(match, titleEl);
    const pathEl = container.createDiv({ text: comp.folder.path });
    applyStyles(pathEl, { fontSize: "11px", color: "var(--text-muted)", fontFamily: "var(--font-monospace)", opacity: "0.7" });
  }
  onChooseItem(comp) {
    this.onChoose(comp);
  }
};
async function loadComponentBundle(container, componentData, app, plugin) {
  const entrypointPath = `${componentData.folder.path}/${componentData.manifest.entrypoint}`;
  const bundleExists = await app.vault.adapter.exists(entrypointPath);
  if (!bundleExists) {
    throw new Error(`Entrypoint not found: ${entrypointPath}`);
  }
  const checkPermission = (type) => {
    var _a;
    const id = componentData.manifest.name;
    const perms = (_a = plugin.settings.componentPermissions) == null ? void 0 : _a[id];
    if (!perms || perms[type] !== true) {
      new import_obsidian.Notice(`[Access Control] Access Denied: ${id} attempted to access ${type}. Permission must be granted in Settings.`);
      throw new Error(`Permission Denied: ${type} is locked for ${id}.`);
    }
  };
  const platformAPI = {
    env: { type: "obsidian" },
    cli: {
      exec: async (endpoint) => {
        checkPermission("cli");
        try {
          const res = await (0, import_obsidian.requestUrl)({ url: `http://127.0.0.1:7777/exec?cmd=${encodeURIComponent(endpoint)}` });
          return { stdout: res.text, stderr: "", code: 0 };
        } catch (e2) {
          return { stdout: "", stderr: String(e2), code: 1 };
        }
      }
    },
    hermes: {
      ensureServer: async (port = 7777) => {
        checkPermission("cli");
        try {
          const res = await (0, import_obsidian.requestUrl)({ url: `http://127.0.0.1:${port}/health` });
          return res.status === 200;
        } catch (e2) {
          return false;
        }
      }
    },
    workspace: {
      insertIntoActiveNote: async (text) => {
        const mdView = app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (mdView && mdView.editor) {
          mdView.editor.replaceSelection(`
${text}
`);
          new import_obsidian.Notice("Inserted PDF Callout into active note!");
          return true;
        }
        const activeFile = app.workspace.getActiveFile();
        if (activeFile instanceof import_obsidian.TFile) {
          const existing = await app.vault.read(activeFile);
          await app.vault.modify(activeFile, `${existing}

${text}
`);
          new import_obsidian.Notice(`Appended PDF Callout to ${activeFile.basename}!`);
          return true;
        }
        return false;
      },
      popoutLeaf: () => {
        var _a;
        const targetLeaf = app.workspace.getLeavesOfType(VIEW_TYPE_GREX).find((l2) => {
          var _a2;
          return l2.view instanceof GrexComponentView && ((_a2 = l2.view.componentData) == null ? void 0 : _a2.manifest.name) === componentData.manifest.name;
        }) || ((_a = app.workspace.getActiveViewOfType(GrexComponentView)) == null ? void 0 : _a.leaf);
        if (targetLeaf) {
          const workspaceExtended = app.workspace;
          if (typeof workspaceExtended.moveLeafToPopout === "function") {
            workspaceExtended.moveLeafToPopout(targetLeaf);
            new import_obsidian.Notice(`Detached ${componentData.manifest.name} into native pop-out panel!`);
          }
        }
      }
    },
    fs: {
      read: async (path) => {
        checkPermission("fs");
        return await app.vault.adapter.read(path);
      },
      write: async (path, data) => {
        checkPermission("fs");
        return await app.vault.adapter.write(path, data);
      },
      exists: async (path) => {
        checkPermission("fs");
        return await app.vault.adapter.exists(path);
      },
      list: async (path) => {
        checkPermission("fs");
        return (await app.vault.adapter.list(path)).files;
      },
      mkdir: async (path) => {
        checkPermission("fs");
        if (!await app.vault.adapter.exists(path)) {
          await app.vault.adapter.mkdir(path);
        }
      },
      delete: async (path) => {
        checkPermission("fs");
        if (await app.vault.adapter.exists(path)) {
          await app.vault.adapter.remove(path);
        }
      },
      rename: async (oldPath, newPath) => {
        checkPermission("fs");
        if (await app.vault.adapter.exists(oldPath)) {
          await app.vault.adapter.rename(oldPath, newPath);
        }
      },
      getResourceUrl: (path) => {
        checkPermission("fs");
        const file = app.vault.getAbstractFileByPath(path);
        return file instanceof import_obsidian.TFile ? app.vault.getResourcePath(file) : null;
      }
    },
    os: {
      write: async (filePath, data) => {
        checkPermission("fs");
        await app.vault.adapter.write(filePath, data);
      },
      rename: async (oldPath, newPath) => {
        checkPermission("fs");
        await app.vault.adapter.rename(oldPath, newPath);
      }
    },
    keychain: {
      list: async () => {
        checkPermission("keychain");
        const storage = app.secretStorage;
        if (storage && typeof storage.listSecrets === "function") {
          return await storage.listSecrets();
        } else if (storage && storage.secrets) {
          return Object.keys(storage.secrets);
        }
        return [];
      },
      get: async (key) => {
        checkPermission("keychain");
        const storage = app.secretStorage;
        if (storage && typeof storage.getSecret === "function") {
          return await storage.getSecret(key);
        }
        const saved = app.loadLocalStorage("grex_" + key);
        return typeof saved === "string" ? saved : null;
      },
      set: async (key, val) => {
        checkPermission("keychain");
        const storage = app.secretStorage;
        if (storage && typeof storage.setSecret === "function") {
          await storage.setSecret(key, val);
        } else {
          app.saveLocalStorage("grex_" + key, val);
        }
      },
      delete: async (key) => {
        checkPermission("keychain");
        const storage = app.secretStorage;
        if (storage && typeof storage.deleteSecret === "function") {
          await storage.deleteSecret(key);
        } else {
          app.saveLocalStorage("grex_" + key, "");
        }
      }
    }
  };
  const winExtended = window;
  winExtended.grexPlatformAPI = platformAPI;
  const bundleFile = app.vault.getAbstractFileByPath(entrypointPath);
  if (!(bundleFile instanceof import_obsidian.TFile)) {
    throw new Error(`Entrypoint not found: ${entrypointPath}`);
  }
  const bundleUrl = `${app.vault.getResourcePath(bundleFile)}?t=${Date.now()}`;
  const importUrl = bundleUrl;
  const dynamicImport = new Function("url", "return import(url);");
  const module2 = await dynamicImport(importUrl);
  const mountFn = module2.mount_app || module2.default;
  if (typeof mountFn !== "function") {
    throw new Error(`Bundle at ${entrypointPath} does not export a mount_app function.`);
  }
  const unmountResult = mountFn(container, {
    app,
    plugin,
    componentData,
    platformAPI,
    preact: preact_module_exports
  });
  return typeof unmountResult === "function" ? unmountResult : () => {
  };
}
var GrexComponentView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.componentData = null;
    this.unmountFn = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_GREX;
  }
  getDisplayText() {
    return this.componentData ? this.componentData.manifest.name : "GREX Component";
  }
  getIcon() {
    var _a;
    return ((_a = this.componentData) == null ? void 0 : _a.manifest.icon) || "box";
  }
  setComponentData(data) {
    this.componentData = data;
  }
  getState() {
    return {
      componentPath: this.componentData ? this.componentData.folder.path : ""
    };
  }
  async setState(state, result) {
    const compPath = (state == null ? void 0 : state.componentPath) || "";
    if (compPath) {
      if (!this.plugin.manifestCache.has(compPath)) {
        await this.plugin.refreshCache();
      }
      const found = this.plugin.manifestCache.get(compPath);
      if (found) {
        this.componentData = found;
        await this.onOpen();
      }
    }
    await super.setState(state, result);
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("grex-nexus-view-container");
    if (!this.componentData) {
      const emptyEl = container.createDiv({ text: "No component loaded." });
      applyStyles(emptyEl, { padding: "20px", color: "var(--text-muted)" });
      return;
    }
    try {
      if (this.unmountFn) {
        this.unmountFn();
        this.unmountFn = null;
      }
      this.unmountFn = await loadComponentBundle(container, this.componentData, this.app, this.plugin);
    } catch (err) {
      console.error("[GrexNexus] \u274C Component Load Error:", err);
      container.empty();
      const errBox = container.createDiv();
      applyStyles(errBox, { padding: "20px", color: "var(--text-error)" });
      errBox.createEl("h3", { text: "Component Load Error" });
      errBox.createEl("pre", { text: String(err) });
    }
  }
  async onClose() {
    if (this.unmountFn) {
      this.unmountFn();
      this.unmountFn = null;
    }
    this.contentEl.empty();
  }
};
var GrexDashboardView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_GREX_DASHBOARD;
  }
  getDisplayText() {
    return "GREX Dashboard";
  }
  getIcon() {
    return "layout-dashboard";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("grex-nexus-view-container");
    const header = container.createDiv();
    applyStyles(header, { padding: "16px", borderBottom: "1px solid var(--background-modifier-border)" });
    header.createEl("h2", { text: "GREX Dashboard" });
    const sub = header.createEl("p", { text: "Manage and launch active vault micro-applications." });
    sub.addClass("grex-text-muted");
    const grid = container.createDiv();
    applyStyles(grid, { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: "16px", padding: "16px" });
    this.plugin.manifestCache.forEach((comp) => {
      const card = grid.createDiv();
      card.addClass("grex-nexus-component-card");
      const cardHeader = card.createDiv();
      applyStyles(cardHeader, { display: "flex", alignItems: "center", gap: "8px", marginBottom: "8px" });
      const iconSpan = cardHeader.createDiv();
      (0, import_obsidian.setIcon)(iconSpan, comp.manifest.icon || "package");
      cardHeader.createEl("strong", { text: comp.manifest.name });
      if (comp.manifest.description) {
        const desc = card.createEl("p", { text: comp.manifest.description });
        desc.addClass("grex-text-muted");
      }
      const btn = card.createEl("button", { text: "Open Component" });
      btn.onclick = () => {
        void this.plugin.activateComponentView(comp);
      };
    });
  }
};
var GrexNexusPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.manifestCache = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_GREX, (leaf) => new GrexComponentView(leaf, this));
    this.registerView(VIEW_TYPE_GREX_DASHBOARD, (leaf) => new GrexDashboardView(leaf, this));
    this.addRibbonIcon("boxes", "Launch Component", () => {
      this.openComponentSelector();
    });
    this.addCommand({
      id: "open-component-selector",
      name: "Launch Component",
      callback: () => {
        this.openComponentSelector();
      }
    });
    this.addCommand({
      id: "open-grex-dashboard",
      name: "Open Dashboard",
      callback: () => {
        void this.activateDashboard();
      }
    });
    this.addCommand({
      id: "provision-dependencies",
      name: "Component Dependencies",
      callback: () => {
        new ProvisioningModal(this.app, this.manifestCache).open();
      }
    });
    this.registerMarkdownCodeBlockProcessor("grex-component", (source, el, ctx) => {
      this.renderComponentCodeBlock(source, el, ctx);
    });
    this.addSettingTab(new GrexNexusSettingTab(this.app, this));
    await this.refreshCache();
  }
  async loadSettings() {
    const loadedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async refreshCache() {
    this.manifestCache.clear();
    for (const compsDir of ["components", "GREX.datacore/components"]) {
      try {
        if (await this.app.vault.adapter.exists(compsDir)) {
          const listResult = await this.app.vault.adapter.list(compsDir);
          for (const folderPath of listResult.folders) {
            const grexJsonPath = `${folderPath}/grex.json`;
            const manifestJsonPath = `${folderPath}/manifest.json`;
            let manifest = null;
            const targetJsonPath = await this.app.vault.adapter.exists(grexJsonPath) ? grexJsonPath : await this.app.vault.adapter.exists(manifestJsonPath) ? manifestJsonPath : null;
            if (targetJsonPath) {
              try {
                const content = await this.app.vault.adapter.read(targetJsonPath);
                manifest = JSON.parse(content);
                if (!manifest.entrypoint) {
                  manifest.entrypoint = "dist/bundle.es.js";
                }
              } catch (e2) {
              }
            }
            if (manifest && manifest.name) {
              const folderObj = this.app.vault.getAbstractFileByPath(folderPath);
              if (folderObj instanceof import_obsidian.TFolder) {
                this.manifestCache.set(folderPath, {
                  folder: folderObj,
                  manifest
                });
              }
            }
          }
        }
      } catch (e2) {
      }
    }
  }
  openComponentSelector() {
    const components = Array.from(this.manifestCache.values());
    if (components.length === 0) {
      new import_obsidian.Notice("No GREX components found in vault. Place components inside components/ or GREX.datacore/components/.");
      return;
    }
    new ComponentSelectorModal(this.app, components, (comp) => {
      void this.activateComponentView(comp);
    }).open();
  }
  async activateComponentView(componentData) {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_GREX).find((l2) => {
      var _a;
      return l2.view instanceof GrexComponentView && ((_a = l2.view.componentData) == null ? void 0 : _a.folder.path) === componentData.folder.path;
    });
    if (!leaf) {
      leaf = workspace.getLeaf("tab");
    }
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE_GREX,
        active: true,
        state: { componentPath: componentData.folder.path }
      });
      if (leaf.view instanceof GrexComponentView) {
        leaf.view.setComponentData(componentData);
        await leaf.view.onOpen();
        workspace.setActiveLeaf(leaf, { focus: true });
      }
    }
  }
  async activateDashboard() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_GREX_DASHBOARD);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeaf("tab");
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_GREX_DASHBOARD, active: true });
      }
    }
    if (leaf) {
      workspace.setActiveLeaf(leaf, { focus: true });
    }
  }
  renderComponentCodeBlock(source, el, _ctx) {
    el.empty();
    const trimmed = source.trim();
    let targetComponent = null;
    for (const comp of this.manifestCache.values()) {
      if (comp.manifest.name.toLowerCase() === trimmed.toLowerCase() || comp.folder.path === trimmed) {
        targetComponent = comp;
        break;
      }
    }
    if (!targetComponent) {
      const errDiv = el.createDiv({ text: `GREX Component not found: "${trimmed}"` });
      applyStyles(errDiv, { padding: "10px", color: "var(--text-error)" });
      return;
    }
    const container = el.createDiv();
    container.addClass("grex-nexus-view-container");
    applyStyles(container, { minHeight: "350px", position: "relative" });
    void loadComponentBundle(container, targetComponent, this.app, this);
  }
};
var GrexNexusSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [
      {
        id: "githubToken",
        name: "GitHub Personal Access Token",
        description: "Used for downloading components from private or rate-limited repositories."
      },
      {
        id: "targetFolder",
        name: "Component Installation Folder",
        description: "Vault directory where remote components are indexed."
      }
    ];
  }
  display() {
    this.renderSettings();
  }
  renderSettings() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Configuration").setHeading();
    new import_obsidian.Setting(containerEl).setName("GitHub Personal Access Token").setDesc("Used for pulling release assets.").addText((text) => text.setPlaceholder("ghp_...").setValue(this.plugin.settings.githubToken).onChange(async (value) => {
      this.plugin.settings.githubToken = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Component Installation Folder").setDesc("Directory path where components are indexed.").addText((text) => text.setValue(this.plugin.settings.targetFolder).onChange(async (value) => {
      this.plugin.settings.targetFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Hermes Sidecar Authentication Token").setDesc("Shared Bearer token for authenticating host calls with Hermes Sidecar IPC daemon.").addText((text) => text.setPlaceholder("Enter sidecar token...").setValue(this.plugin.settings.sidecarToken).onChange(async (value) => {
      this.plugin.settings.sidecarToken = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Hermes Sidecar URL").setDesc("Base URL for Hermes Sidecar IPC daemon (default: http://localhost:7777).").addText((text) => text.setValue(this.plugin.settings.sidecarUrl).onChange(async (value) => {
      this.plugin.settings.sidecarUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Installed Components").setHeading();
    const uniqueComponents = Array.from(this.plugin.manifestCache.values());
    if (uniqueComponents.length === 0) {
      const noComps = containerEl.createEl("p", { text: "No native components installed." });
      applyStyles(noComps, { color: "var(--text-muted)", padding: "20px", textAlign: "center" });
    } else {
      const libraryContainer = containerEl.createDiv();
      applyStyles(libraryContainer, { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: "16px", padding: "10px 0" });
      uniqueComponents.forEach((comp) => {
        const card = libraryContainer.createDiv();
        card.addClass("grex-nexus-component-card");
        const header = card.createDiv();
        applyStyles(header, { display: "flex", alignItems: "center", gap: "12px", marginBottom: "12px" });
        const iconBox = header.createDiv();
        applyStyles(iconBox, { width: "36px", height: "36px", borderRadius: "8px", background: "var(--background-modifier-form-field)", display: "flex", alignItems: "center", justifyContent: "center" });
        (0, import_obsidian.setIcon)(iconBox, comp.manifest.icon || "package");
        const titleBox = header.createDiv();
        titleBox.createDiv({ text: comp.manifest.name });
        const pathBox = card.createDiv({ text: comp.folder.path });
        pathBox.addClass("grex-text-muted");
        const requestedPerms = comp.manifest.permissions || [];
        if (requestedPerms.length > 0) {
          const privacyBox = card.createDiv();
          applyStyles(privacyBox, { marginTop: "12px", borderTop: "1px solid var(--background-modifier-border)", paddingTop: "12px" });
          privacyBox.createDiv({ text: "Privacy & Security" });
          const perms = this.plugin.settings.componentPermissions[comp.manifest.name] || {};
          requestedPerms.forEach((permType) => {
            let name = permType;
            let desc = "";
            if (permType === "fs") {
              name = "Filesystem Storage";
              desc = "Allow access to Vault";
            } else if (permType === "keychain") {
              name = "Keychain & Security";
              desc = "Allow access to Credentials";
            } else if (permType === "cli") {
              name = "Terminal & CLI";
              desc = "Allow command execution";
            }
            new import_obsidian.Setting(privacyBox).setName(name).setDesc(desc).addToggle((toggle) => toggle.setValue(perms[permType] === true).onChange(async (val) => {
              if (!this.plugin.settings.componentPermissions[comp.manifest.name]) {
                this.plugin.settings.componentPermissions[comp.manifest.name] = {};
              }
              this.plugin.settings.componentPermissions[comp.manifest.name][permType] = val;
              await this.plugin.saveSettings();
            }));
          });
        }
        const footer = card.createDiv();
        applyStyles(footer, { display: "flex", justifyContent: "flex-end", marginTop: "16px", gap: "8px" });
        new import_obsidian.ButtonComponent(footer).setButtonText("Purge").setDestructive().onClick(async () => {
          await this.app.fileManager.trashFile(comp.folder);
          new import_obsidian.Notice(`Removed ${comp.manifest.name}`);
          await this.plugin.refreshCache();
          this.renderSettings();
        });
      });
    }
  }
};
